---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmos
  labels:
    app: farmos
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: farmos
  template:
    metadata:
      labels:
        app: farmos
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: "always"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/drupal/web/sites
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: farmos
